service: drivers

provider:
  name:    aws
  runtime: nodejs6.10
  region:  eu-west-2
  stage:   ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment:
    resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table"
    SALT:     "q?Ufd{Ep8>lPQ*~mc|bVT$<*;zI?r(:3lkVk~;pT:**dqbw}.nv334W`@9Z#,ki9"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "${self:provider.environment.resource}/collections"
        - "${self:provider.environment.resource}/collections/index/*"
        - "${self:provider.environment.resource}/consignments"
        - "${self:provider.environment.resource}/consignments/index/*"
        - "${self:provider.environment.resource}/dropOffs"
        - "${self:provider.environment.resource}/dropOffs/index/*"
        - "${self:provider.environment.resource}/quotes"
        - "${self:provider.environment.resource}/quotes/index/*"
        - "${self:provider.environment.resource}/signatures"
        - "${self:provider.environment.resource}/signatures/index/*"
        - "${self:provider.environment.resource}/userOrganisations"
        - "${self:provider.environment.resource}/userOrganisations/index/*"
        - "${self:provider.environment.resource}/vehicles"
        - "${self:provider.environment.resource}/vehicles/index/*"
        - "${self:provider.environment.resource}/waste"
        - "${self:provider.environment.resource}/waste/index/*"
        - "${self:provider.environment.resource}/wasteFacilities"
        - "${self:provider.environment.resource}/wasteFacilities/index/*"

plugins:
  - serverless-webpack

custom:
  defaultStage: local
  profiles:
    local:      doctorshelp-local
    staging:    doctorshelp-staging
    production: doctorshelp-production
  webpack: ./config/webpack.config.js

functions:

  auth-list:
    handler:  authenticate.listHandler

  auth-update:
    handler:  authenticate.updateHandler

# DRIVERS
  login:
    handler: login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  consignmentsList:
    handler: consignments-list.handler
    events:
      - http:
          path:  consignments
          method: get
          cors: true
          authorizer:  auth-list

  collectionsList:
    handler: collections-list.handler
    events:
      - http:
          path:  collections
          method: get
          cors: true
          authorizer:  auth-list

  dropOffsList:
    handler: drop-offs-list.handler
    events:
      - http:
          path:  drop-offs
          method: get
          cors: true
          authorizer:  auth-list

  collectionsUpdate:
    handler: collections-update.handler
    events:
      - http:
          path:  collections/{collectionId}
          method: put
          cors: true
          authorizer:  auth-update

  dropOffsUpdate:
    handler: drop-offs-update.handler
    events:
      - http:
          path:  drop-offs/{dropOffId}
          method: put
          cors: true
          authorizer:  auth-update