local:
  s3Bucket: 'com.doctorshelp.local.'
  region:   eu-central-1
  userpool: "arn:aws:cognito-idp:eu-west-2:920932936597:userpool/eu-west-2_ldblb0DTS"
  version:  1.0.0
  SALT:     "q?Ufd{Ep8>lPQ*~mc|bVT$<*;zI?r(:3lkVk~;pT:**dqbw}.nv334W`@9Z#,ki9"
staging:
  s3Bucket: 'com.doctorshelp.staging.'
  region:   eu-west-1
  userpool: "arn:aws:cognito-idp:eu-west-2:920932936597:userpool/eu-west-2_WrzDEo709"
  version:  1.0.0
  SALT:     "q?Ufd{Ep8>lPQ*~mc|bVT$<*;zI?r(:3lkVk~;pT:**dqbw}.nv334W`@9Z#,ki9"
sandbox:
  s3Bucket: 'com.doctorshelp.sandbox.'
  region:   us-west-2
  userpool: "arn:aws:cognito-idp:eu-west-2:920932936597:userpool/eu-west-2_EUWi4ARBv"
  version:  1.0.0
  SALT:     "q?Ufd{Ep8>lPQ*~mc|bVT$<*;zI?r(:3lkVk~;pT:**dqbw}.nv334W`@9Z#,ki9"
production:
  s3Bucket: 'com.doctorshelp.production.'
  region:   eu-west-2
  userpool: "arn:aws:cognito-idp:eu-west-2:920932936597:userpool/eu-west-2_ZOfj5ShuH"
  version:  1.0.0
  SALT:     "q?Ufd{Ep8>lPQ*~mc|bVT$<*;zI?r(:3lkVk~;pT:**dqbw}.nv334W`@9Z#,ki9"